### ISSUE TITLE
A simple explaination of wasserstein distance

### ISSUE THREAD

**Issue by FengHZ** [FengHZ/BlogComments#13]
https://fenghz.github.io/Wasserstein-distance/

**Comment by FengHZ** [comment]
Here you can leave a comment

**Comment by eyuansu62** [comment]
您好,你公式里的#是啥意思呀

**Comment by FengHZ** [comment]
#表示由T诱导的对度量空间的变换，对于变换T，诱导度量空间的变换 $T_#$ 满足 $T_#(u)(E)=u(T^{-1}(E))$

**Comment by eyuansu62** [comment]
嗷嗷，那请问是p等于1和正态分布可以求解吗，但是p等于2不是就相当于欧几里得距离了吗，另外这个纬度d指的是数据的纬度吗？多谢您的回复了!------------------ 原始邮件 ------------------
发件人: "FengHZ"<notifications@github.com>
发送时间: 2019年11月14日(星期四) 晚上10:00
收件人: "FengHZ/BlogComments"<BlogComments@noreply.github.com>;
抄送: "eyuansu62"<772468951@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [FengHZ/BlogComments] A simple explaination of wassersteindistance (#13)



#表示由T诱导的对度量空间的变换，对于变换T，诱导度量空间的变换  满足 
 
&mdash;

**Comment by FengHZ** [comment]
对于正态分布，p=2的时候可解，不是欧氏距离，要考虑方差的

**Comment by eyuansu62** [comment]
那请问d纬度指的是什么呢？



---Original---

**Comment by FengHZ** [comment]
应该就是R^n的n，这里显示错误了，我修改一下

**Comment by eyuansu62** [comment]
您好, 当d=1时,F−1(z)−G−1(z) 这里的F是怎么得到的呀
